baseurl = "http://ilonabrand.com"
languageCode = "en-us"
theme = "curlew"

title = "Ilona Brand"
MetaDataFormat = "toml"

canonifyURLs = true
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
PygmentsCodeFences = true

